notifications:
  email:
    on_success: never
    on_failure: change

script:
  - script/travis-ci-build.sh

git:
  depth: 10

sudo: false
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES=""

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - hunspell
    - hunspell-en-us

before_install:
  - script/travis-ci-before-install.sh

branches:
  only:
    - master
